spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 10
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8085

com:
  novosad:
    itemsOnPage: 50